### ISSUE TITLE
Criar no Figma as telas de acordo com os requisitos funcionais

### ISSUE THREAD

**Issue by rosoares** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t11-pmv-ads-2023-1-e1-proj-web-t11-03#2]
Criar no Figma as interfaces de acordo com os requisitos funcionais (Não tem problema caso precise adicionar algo a interface que não está descrito no requisito funcional)

**Comment by giuliabriao** [comment]
Feito!
