### ISSUE TITLE
Definir em encontro síncrono do time as responsabilidades de cada um

### ISSUE THREAD

**Issue by rosoares** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t11-pmv-ads-2023-1-e1-proj-web-t11-03#4]
Definir em um encontro síncrono com todo o time as responsabilidades de cada um no projeto. E após isso criar novos Issues para controle das tarefas

**Comment by giuliabriao** [comment]
Definido no ultimo encontro síncrono (18/04)

**Comment by giuliabriao** [comment]
Definido no ultimo encontro síncrono (18/04)
